sonar.projectKey=StartBet_st-core-ui
sonar.organization=startbet
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=**/*.config.js,**/*.config.cjs,**/*.config.mjs,**/*.config.ts,**/package.json,**/package-lock.json

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=st-core-ui
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
